import turtle
turtle.speed(1)
turtle.bgcolor('black')
omer=turtle.Turtle()
omer.shape('triangle')
omer.color('orange')
omer.pensize(5)
omer.left(90)
omer.forward(200)
omer.left(90)
omer.shape('circle')
omer.color('white')
omer.forward(150)

natalie=turtle.Turtle()
natalie.color('green')
natalie.pensize(10)
natalie.right(90)
natalie.forward(250)
natalie.color('blue')
natalie.shape('triangle')
natalie.left(90)
natalie.forward(100)
natalie.left(90)
natalie.forward(400)
turtle.mainloop()
